# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 10:20
from __future__ import unicode_literals

from django.db import migrations


def move_hearing_images_to_sections(apps, schema_editor):
    HearingImage = apps.get_model('democracy', 'HearingImage')
    SectionImage = apps.get_model('democracy', 'SectionImage')
    Section = apps.get_model('democracy', 'Section')
    for hearing_image in HearingImage.objects.all():
        first_section = Section.objects.filter(hearing_id=hearing_image.hearing_id).order_by("ordering").first()
        if SectionImage.objects.filter(section=first_section, title=hearing_image.title).exists():
            continue  # Don't create duplicates
        SectionImage.objects.create(
            section=first_section,
            title=hearing_image.title,
            caption=hearing_image.caption,
            width=hearing_image.width,
            height=hearing_image.height,
            image=hearing_image.image,
            ordering=hearing_image.ordering - 100,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0015_add_organization_model'),
    ]

    operations = [
        migrations.RunPython(
            move_hearing_images_to_sections,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='hearingimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hearingimage',
            name='hearing',
        ),
        migrations.RemoveField(
            model_name='hearingimage',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='HearingImage',
        ),
    ]
