# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 11:00
from __future__ import unicode_literals

from django.db import migrations

def move_hearing_comments_to_sections(apps, schema_editor):
    HearingComment = apps.get_model('democracy', 'HearingComment')
    SectionComment = apps.get_model('democracy', 'SectionComment')
    Section = apps.get_model('democracy', 'Section')
    #raise NotImplementedError("...")



class Migration(migrations.Migration):
    
    dependencies = [
        ('democracy', '0016_remove_hearing_image'),
    ]

    operations = [
        migrations.RunPython(
            move_hearing_comments_to_sections,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='hearingcomment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hearingcomment',
            name='hearing',
        ),
        migrations.RemoveField(
            model_name='hearingcomment',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='hearingcomment',
            name='voters',
        ),
        migrations.DeleteModel(
            name='HearingComment',
        ),
    ]
